#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WizarDroid.NET.Resource", IsApplication=false)]

namespace WizarDroid.NET
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040000
			public static int horizontal_line = 2130968576;
			
			// aapt resource value: 0x7f040005
			public static int step_container = 2130968581;
			
			// aapt resource value: 0x7f040003
			public static int vertical_line = 2130968579;
			
			// aapt resource value: 0x7f040001
			public static int wizard_button_bar = 2130968577;
			
			// aapt resource value: 0x7f040004
			public static int wizard_next_button = 2130968580;
			
			// aapt resource value: 0x7f040002
			public static int wizard_previous_button = 2130968578;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public static int wizardroid_basic_wizard = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030002
			public static int action_finish = 2130903042;
			
			// aapt resource value: 0x7f030001
			public static int action_next = 2130903041;
			
			// aapt resource value: 0x7f030000
			public static int action_previous = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
