#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WizarDroid.NET_Sample.Resource", IsApplication=true)]

namespace WizarDroid.NET_Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::WizarDroid.NET.Resource.Id.horizontal_line = global::WizarDroid.NET_Sample.Resource.Id.horizontal_line;
			global::WizarDroid.NET.Resource.Id.step_container = global::WizarDroid.NET_Sample.Resource.Id.step_container;
			global::WizarDroid.NET.Resource.Id.vertical_line = global::WizarDroid.NET_Sample.Resource.Id.vertical_line;
			global::WizarDroid.NET.Resource.Id.wizard_button_bar = global::WizarDroid.NET_Sample.Resource.Id.wizard_button_bar;
			global::WizarDroid.NET.Resource.Id.wizard_next_button = global::WizarDroid.NET_Sample.Resource.Id.wizard_next_button;
			global::WizarDroid.NET.Resource.Id.wizard_previous_button = global::WizarDroid.NET_Sample.Resource.Id.wizard_previous_button;
			global::WizarDroid.NET.Resource.Layout.wizardroid_basic_wizard = global::WizarDroid.NET_Sample.Resource.Layout.wizardroid_basic_wizard;
			global::WizarDroid.NET.Resource.String.action_finish = global::WizarDroid.NET_Sample.Resource.String.action_finish;
			global::WizarDroid.NET.Resource.String.action_next = global::WizarDroid.NET_Sample.Resource.String.action_next;
			global::WizarDroid.NET.Resource.String.action_previous = global::WizarDroid.NET_Sample.Resource.String.action_previous;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public const int firstname = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int firstnameField = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int firstname_form2 = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int form_summary = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int form_wizard_fragment = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int horizontal_line = 2131034122;
			
			// aapt resource value: 0x7f050007
			public const int lastname = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int lastnameField = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int sample_form2_checkbox = 2131034116;
			
			// aapt resource value: 0x7f05000f
			public const int step_container = 2131034127;
			
			// aapt resource value: 0x7f050000
			public const int textView = 2131034112;
			
			// aapt resource value: 0x7f050009
			public const int tutorial_wizard_fragment = 2131034121;
			
			// aapt resource value: 0x7f05000d
			public const int vertical_line = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int wizard_button_bar = 2131034123;
			
			// aapt resource value: 0x7f05000e
			public const int wizard_next_button = 2131034126;
			
			// aapt resource value: 0x7f05000c
			public const int wizard_previous_button = 2131034124;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int form_step_1 = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int form_step_2 = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int form_step_summary = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int formtest = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int tuorial_steps_layout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int tutorial = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int wizardroid_basic_wizard = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int ApplicationName = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int action_finish = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int action_next = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int action_previous = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int chooseasample = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int hint_firstname = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int hint_lastname = 2130968583;
			
			// aapt resource value: 0x7f04000b
			public const int sample_form_checkbox = 2130968587;
			
			// aapt resource value: 0x7f040009
			public const int sample_form_summary = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int sample_form_text = 2130968584;
			
			// aapt resource value: 0x7f04000a
			public const int sample_form_text2 = 2130968586;
			
			// aapt resource value: 0x7f040005
			public const int title_form_wizard = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
